language: python
python:
- '3.4'
before_install:
- openssl aes-256-cbc -K $encrypted_dad7bb02cf2c_key -iv $encrypted_dad7bb02cf2c_iv
  -in config.yaml.enc -out config.yaml -d
- sudo apt-get install -y enchant
install:
- pip install https://github.com/anqxyr/pyscp/zipball/master
- pip install -e .
script: py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
after_success:
- coveralls